---
title: "Noorte meede"
author: "Jüri Lillemets"
date: "November 20, 2017"
output: html_document
---

```{r setup, include = FALSE, eval = TRUE}
# Määra seaded
knitr::opts_chunk$set(include = T, eval = T, echo = F, message = F, warning = F, 
                      fig.asp = .5, fig.width = 10)
# Määra töökaust
knitr::opts_knit$set(root.dir = '/home/jrl')
# Lae pakid ja objektid
library('rsdmx');library('forecast')
load('data/objects/ggplot_themes.Rda')
```

``` {r} 
## Andmed Statistikaametist Eesti kohta
vanused <- setDSD(readSDMX('http://andmebaas.stat.ee/restsdmx/sdmx.ashx/GetData/PMS204/1+2.1+2+3.1+2+3.1+2+3+4+5+6+7+8+9/all?startTime=2003&endTime=2016'),
                 readSDMX('http://andmebaas.stat.ee/restsdmx/sdmx.ashx/GetDataStructure/PMS204'))
vanused <- as.data.frame(vanused, labels = T)
vanused <- vanused[, c(names(vanused)[grep('label.et', names(vanused))], 'obsTime', 'obsValue')]


ars <- vanused[vanused[, 1] == "Hõivatute arv" & 
                     vanused[, 2] == "Kokku" & 
                     vanused[, 4] != "35-39" & 
                     vanused[, 4] != "40-44", 
                   -1]
ars <- reshape(ars, timevar = 'obsTime', idvar = c('DIM3_label.et', 'DIM4_label.et', 'DIM5_label.et'), direction = 'wide')
nimed <- apply(ars[, 1:3], 1, paste, collapse = ' ')
nimed <- gsub(' ', '.', nimed)
ars <- data.frame(t(ars[, 4:9]))
names(ars) <- nimed
#ars <- ars[, !(grepl('kokku', names(ars)))]

rbind(ars, sapply(ars, function(x) forecast(x)$mean))

```